# Generated by Django 2.0 on 2022-06-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectocoderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('clase', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='profes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
    ]
